#!/bin/sh
# git-create-branch <branch_name>
 
if [ $# -ne 1 ]; then
	echo "Usage: ${0} branch_name"
	exit 127
fi
 
branch_name=$1
current_branch=`git branch -a | grep \*`
if [ "${current_branch}" != "* master" ]; then
  git co master 2>&1 >/dev/null
fi

local_branch=`git branch -a | grep remotes/${branch_name} | head -n1`
remote_branch=`git branch -a | grep origin/${branch_name} | tail -n1`

if [ "${remote_branch}" != "  remotes/origin/${branch_name}" ]; then
	git push origin origin:refs/heads/${branch_name}
	git fetch origin
else
	echo "Remote branch 'remotes/origin/${branch_name}' already exists"
fi

if [ "${local_branch}" != "  ${branch_name}" ]; then
	git checkout --track -b ${branch_name} origin/${branch_name}
	git pull
else
	echo "Local branch 'remotes/origin/${branch_name}' already exists!"
fi
